version: "3.8"

services:
  meme_search_pro:
    image: ghcr.io/neonwatty/meme_search_pro:latest
    container_name: meme_search_pro
    environment:
      DATABASE_URL: "postgres://postgres:postgres@meme-search-db:5432/meme_search"
    ports:
      - "${APP_PORT:-3000}:3000" # <--  adjust to desired local port for this service in your .env file
    depends_on:
      meme_search_db:
        condition: service_healthy
    volumes: # <-- any additional meme directory must be mounted here - and placed in the /rails/public/memes directory in the container (see example below)
      - ./meme_search_pro/memes/:/rails/public/memes # <-- example meme directory from the repository
      # -  /route/to/my/personal/additional_memes/:/rails/public/memes/additional_memes # <-- personal meme collection - must be placed inside /rails/public/memes in the container


  image_to_text_generator:
    image: ghcr.io/neonwatty/image_to_text_generator:latest
    container_name: image_to_text_generator
    environment:
      APP_PORT: "${APP_PORT:-3000}"
    expose:
      - "8000"
    volumes: # <-- any additional meme directory must be mounted here - and placed in the /app/public/memes directory in the container (see example below)
      - ./meme_search_pro/memes/:/app/public/memes # <-- example meme directory from the repository
      # -  /route/to/my/personal/additional_memes/:/app/public/memes/additional_memes # <-- personal meme collection - must be placed inside /app/public/memes in the container
      - ./meme_search_pro/db_data/image_to_text_generator:/app/db
      - ./meme_search_pro/models:/root/.cache/huggingface
    deploy:
      resources:
        limits: # <-- roughly tested min memory for cpu usage
          memory: 12GB
        # reservations: # <-- uncomment for gpu usage
        #   devices:
        #     - driver: nvidia
        #       count: 1
        #       capabilities: [gpu]

  meme_search_db:
    image: pgvector/pgvector:pg17
    container_name: meme-search-db # note: must use - and not _ as ActiveRecord uses URI::RFC2396_Parser to parse database URLs
    volumes:
      - ./meme_search_pro/db_data/meme-search-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: meme_search
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
