name: rails tests for meme search pro app

on:
  pull_request:
    branches: ["main"]
    paths:
      - "meme_search_pro/meme_search_app/**"
      - ".github/workflows/pro-app-test.yml"

jobs:
  pro_app_ruby_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false
          working-directory: ./meme_search_pro/meme_search_app

      - name: Install dependencies
        run: gem install bundler && bundle install
        working-directory: ./meme_search_pro/meme_search_app

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman -w3 --no-pager
        working-directory: ./meme_search_pro/meme_search_app

  pro_app_js_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false
          working-directory: ./meme_search_pro/meme_search_app

      - name: Install dependencies
        run: gem install bundler && bundle install
        working-directory: ./meme_search_pro/meme_search_app

      - name: Scan for security vulnerabilities in JavaScript dependencies
        working-directory: ./meme_search_pro/meme_search_app
        run: gem uninstall error_highlight -v 0.3.0 && bin/importmap audit

  pro_app_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false
          working-directory: ./meme_search_pro/meme_search_app

      - name: Install dependencies
        run: gem install bundler && bundle install
        working-directory: ./meme_search_pro/meme_search_app

      - name: Lint code for consistent style
        run: gem uninstall error_highlight -v 0.3.0 && bin/rubocop -f github
        working-directory: ./meme_search_pro/meme_search_app

  pro_app_tests:
    runs-on: ubuntu-latest

    services:
      meme-search-db:
        image: pgvector/pgvector:pg17
        env:
          POSTGRES_DB: meme_search
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl libjemalloc2 libvips postgresql-client

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: false
          working-directory: ./meme_search_pro/meme_search_app

      - name: Install dependencies
        run: gem install bundler && bundle install
        working-directory: ./meme_search_pro/meme_search_app

      - name: Run tests
        working-directory: ./meme_search_pro/meme_search_app
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432
        run: bin/rails db:test:prepare test test:system

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
