name: "pro app build"
on:
  workflow_dispatch:

jobs:
  build_pro_app:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        working-directory: ./meme_search_pro/image_to_text_generator
        run: |
          pip install -r requirements.txt

      - name: Log in to Github Docker Image Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.actor }}/image_to_text_generator
          tags: type=ref,event=tag
          flavor: latest=true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Upload for AMD64 and ARM64
        uses: docker/build-push-action@v4
        with:
          context: ./meme_search_pro/image_to_text_generator
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/neonwatty/image_to_text_generator:latest
