name: python tests for meme search pro image to text generator

on:
  pull_request:
    branches: ["main"]
    paths:
      - "meme_search_pro/image_to_text_generator/**"

jobs:
  ruff:
    name: lint with ruff
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      - uses: chartboost/ruff-action@v1
        with:
          args: "format --check"
          config: .ruff.toml
  test:
    name: run pytest
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.test
          pip install -r requirements.txt
      - name: Run pytest
        run: |
          PYTHONPATH=. python3.10 -m pytest tests/
