name: image to text generator tests for pro app

on:
  pull_request:
    branches: ["main"]
    paths:
      - "meme_search_pro/image_to_text_generator/**"
      - ".github/workflows/pro-image-to-text-test.yml"

jobs:
  image_to_text_lint:
    name: image_to_text_lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
      - uses: chartboost/ruff-action@v1
        with:
          args: "check --fix"
          config: .ruff.toml
          working-directory: ./meme_search_pro/image_to_text_generator/app
  image_to_text_tests:
    name: run pytest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"
      - name: Install dependencies
        working-directory: ./meme_search_pro/image_to_text_generator
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.test
          pip install -r requirements.txt
      - name: Run pytest
        working-directory: ./meme_search_pro/image_to_text_generator
        run: |
          PYTHONPATH=. python3.12 -m pytest tests/test_app.py
