# name: "pro app build"
# on:
#   workflow_dispatch:
#   pull_request:
#   push:
#     branches: ["main"]
#     paths:
#       - "meme_search_pro/meme_search_app/**"

name: "pro app build"
on:
  workflow_dispatch:

jobs:
  Build_And_Push:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          working-directory: ./meme_search_pro/meme_search_app
          bundler-cache: true
      - run: bundle exec rake

      - name: Log in to Github Docker Image Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.actor }}/meme_search_pro
          tags: type=ref,event=tag
          flavor: latest=true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Upload for AMD64 and ARM64
        uses: docker/build-push-action@v4
        with:
          context: ./meme_search_pro/meme_search_app
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            meme_search_pro:latest
          labels: ${{ steps.meta.outputs.labels }}
