name: python tests for meme search standard app

on:
  workflow_dispatch:
  pull_request:
    branches: ["main"]
    paths:
      - "meme_search/meme_search_app/**"

jobs:
  standard_app_lint:
    name: lint with ruff
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install Ruff and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run Ruff linting
        run: |
          ruff format --check --config ./meme_search/.ruff.toml ./meme_search/meme_search_app

  standard_app_tests:
    name: run pytest
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd meme_search
          python -m pip install --upgrade pip
          pip install -r requirements.test
          pip install -r requirements.txt

      - name: Run pytest
        run: |
          cd meme_search &&
          PYTHONPATH=. python3.10 -m pytest tests/test_app.py
          # PYTHONPATH=. python3.10 -m pytest tests/utilities/test_add_remove.py ## requires large runner
