name: "Standard App Build"

on:
  workflow_dispatch:

jobs:
  standard_app_build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Log in to Github Docker Image Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/${{ github.actor }}/meme-search
          # ${{ secrets.DOCKERHUB_USERNAME }}/meme-search
          tags: type=ref,event=tag
          flavor: latest=true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Upload for AMD64 and ARM64
        uses: docker/build-push-action@v4
        with:
          context: ./meme_search/
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
